### ISSUE TITLE
Please create an AppData file for Budgie

### ISSUE THREAD

**Issue by hughsie** [ikeydoherty/budgie#23]
Please consider writing and installing an AppData file with the application description and some screenshots, else Budgie looks really bad in the GNOME and KDE Software Centers. We'd love to showcase more applications, but without the extra data file we can't. See http://people.freedesktop.org/~hughsient/appdata/ for details; thanks!

Richard

**Comment by williamjmorenor** [comment]
Hi 

I have take ownership of the budgie package in Fedora repos, I have written a appdate.xml file, if you are fine to include it in the repo I can make the pull request.

**Comment by ikeydoherty** [comment]
@williamjmorenor yes please. At the time of this bug Budgie was much smaller, I believe now is an appropriate time for an appdata file!
